language: node_js
sudo: false
node_js:
- 10
- 8
- 6
os:
- windows
- linux
- osx
before_install:
- npm run setup:ci
install:
- npm run setup
script:
- npm run lint
- npm run test:ci
deploy:
  provider: npm
  email: services@serverless.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: serverless/utils
  api_key:
    secure: cAcSHxO4Vi5oKwcXA0W5eq8/CVkwZ5W0rRfM3Fi2P4/Dz6cDkQKa2MkY2jDn6j67gL0fQzHvmoX4WmYkRjKEVFKjDk/pLT7E2vIklF20PT1LZ+gin+jldJSsY1ZVQj0ZpRA6qkB6IHVjN/mALY3UA9cWTE6GJ+CigGqWdBVwk682pRnygR4xot2hCQ75HAzaXCiTYwjGMvYPUTspKXxCfmqewZ0FqGxv2lfbMNXpwDLKJKIB0YAl6ySIygZViIx+7buRNPMord91X7geAAcbgPx10dwc787+Q0yHWhYzN/19jaUEaxgfao2Kk2TkMtSGAoOhnqGtEkLTQXCg8zd6X/rW0IyTzisQ5y7uj6ln9pXJCZ3WFCyC7MANVWKdR6PHw/1XRtEEaBs83R0JFxJhCn1Bwj7+optI9d3XWDPgxCDVXbzPk7PetR6OaQR1BkRj2yEchPNa0dcU5m/5TEZDtL8ZOSC5LKhdXTTGCz6VvowE9iZoh2ZYevs28kiREYeTUXiGEOYxqneaFliFneFuHL1ct6utQhNrL6IzxKI91HOPeVqp50uxyzKnWdw3HXMMhvOqh+uDXChVGsLV3oq3GaFGSAkeYj7IjXgH/V/mZHhjP6Oj4cKJ0Gefo0uoFmh7Jw/0h3xGUDQHNxnC5T+/6bLfVVYi7TNgDVcOM29HIZ8=
