language: node_js
sudo: false
node_js:
- 10
- 8
- 6
- 4
install:
- npm install
script:
- npm run clean
- npm run build
- npm run lint
- npm test
deploy:
  provider: npm
  email: services@serverless.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: serverless/utils
  api_key:
    secure: otetEYi3u6RE+OHcsOqNaSfU9GHNWRCRwdHGLcFi3Aj6/SaOieygvz/LbnksR1ejog8ARDjQyJxct/O3EQ0+rSyOk+KAVLLYsxi36DNP8K4jXF1xaHsLtKYeEySTI4h173QExHCiwJvaXbp8elxMtuVRYQcjb8xj0s7XGG0Kb6vuKTMR8P/7mG7w4vO2uRcfOcBU43aF7AggOjXrDv0GJR4+X/TMeNbExpNPaSukRvnertSM00arqe8uM6rV1OEiK6Tqq6MfDNFAFRzI4N9bEw/q2HRrvhX9fcqh/yRfKnoUCQPZSHDXYwk4jHeDZyTTvHS2gu8TBBPJNpXMQiLyWUdkJIsrpziskJtTrl3b/piUkHnTQZ+qKK3bmoXaKYj24mjSjEHxl7WDcrtd4P3OTSH7t4Tk2z37J4iOZ/AklgudcGOzBVvlHVyt2JzPNM1jdQ15bLH+YcNgQniuxPt6QSJ9reB9XfcqrK15hTdlzwrodM0tL0pn0E0aFy65rXYjfLwnU1xHoqlpvl59B1sBcJp0XEnOAl+SdwBAhVWbsfJYpSjz/70maoB/XRVk213RZU7gfghEzLmhraZXTkg9/KFTOOfbRqnS/iPNMZ6KPgdXfIqNyRjadudaK3y9sbguh7wcAaLZ4ZY5jHczxat6nCnMUJGPNe5VH2yVQqXlFoE=
